var ME={name:'Sarah Chen',role:'Senior Carer'};
function authH(){var h={'Content-Type':'application/json'};var t=localStorage.getItem('access_token');if(t)h['Authorization']='Bearer '+t;return h;}
function authHF(){var h={};var t=localStorage.getItem('access_token');if(t)h['Authorization']='Bearer '+t;return h;}
function esc(s){return(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function ini(n){return(n||'?').split(' ').map(function(w){return w[0];}).join('').toUpperCase().slice(0,2);}
function scrollBottom(){var el=document.getElementById('chat-messages');el.scrollTop=el.scrollHeight;}
function fmtSize(b){if(b<1024)return b+'B';if(b<1048576)return(b/1024).toFixed(1)+'KB';return(b/1048576).toFixed(1)+'MB';}
var DEMO_CONVS=[
  {id:1,name:'Care Team - Floor 2',category:'team',last_message:"Perfect, I'll check on her in 10 minutes",last_message_at:'9:32 AM',unread_count:3,sub:'Floor 2 - 4 participants',color:'#2ec4b6',online:true},
  {id:2,name:'Sarah Chen',category:'team',last_message:"Can you help me with Mrs. Johnson's medication schedule?",last_message_at:'11:15 AM',unread_count:1,sub:'Senior Carer',color:'#7c3aed',online:true},
  {id:3,name:'Resident Care: Dorothy Williams',category:'resident',last_message:'Daily care report completed successfully',last_message_at:'Yesterday',unread_count:0,sub:'Room 106',color:'#db2777',online:false},
  {id:4,name:'Night Shift Handover',category:'team',last_message:'All residents sleeping peacefully.',last_message_at:'Yesterday',unread_count:0,sub:'Night Team',color:'#059669',online:false},
  {id:5,name:'Emergency Alerts',category:'alerts',last_message:'Fire drill scheduled for tomorrow at 2 PM',last_message_at:'2 days ago',unread_count:0,sub:'System Alerts',color:'#ef4444',online:false},
];
var DEMO_MSGS={
  1:[{id:1,conversation_id:1,sender_name:'Sarah Chen',sender_role:'Senior Carer',content:"Hi team! Mrs. Johnson in room 204 is asking for her afternoon medication. Can someone check on her?",is_self:'false',created_at:'9:30 AM'},{id:2,conversation_id:1,sender_name:'Me',sender_role:'Senior Carer',content:"Perfect, I'll check on her in 10 minutes",is_self:'true',created_at:'9:32 AM'},{id:3,conversation_id:1,sender_name:'Mike Roberts',sender_role:'Nurse',content:"Thanks! I've also updated her care plan with the new medication schedule.",is_self:'false',created_at:'10:15 AM'}],
  2:[{id:4,conversation_id:2,sender_name:'Sarah Chen',sender_role:'Senior Carer',content:"Can you help me with Mrs. Johnson's medication schedule?",is_self:'false',created_at:'11:15 AM'}],
  3:[{id:5,conversation_id:3,sender_name:'Linda Pham',sender_role:'Carer',content:"Daily care report for Dorothy Williams completed. All vitals stable.",is_self:'false',created_at:'3:00 PM'},{id:6,conversation_id:3,sender_name:'Me',sender_role:'Senior Carer',content:"Thank you! I've reviewed the report.",is_self:'true',created_at:'3:05 PM'}],
  4:[{id:7,conversation_id:4,sender_name:'Night Team',sender_role:'Carer',content:"All residents sleeping peacefully. No incidents to report.",is_self:'false',created_at:'10:00 PM'}],
  5:[{id:8,conversation_id:5,sender_name:'System',sender_role:'Admin',content:"Fire drill scheduled for tomorrow at 2 PM. All staff please be prepared.",is_self:'false',created_at:'2 days ago'}],
};
var allConvs=[],filteredConvs=[],currentId=null,currentCat='',localMsgs={},demo=false,pendingFiles=[];
var CAT_CLR={team:'#2ec4b6',resident:'#7c3aed',alerts:'#ef4444'};
var ID_CLR=['#2ec4b6','#7c3aed','#db2777','#059669','#d97706','#0369a1','#dc2626','#9333ea'];
var SC_CLR=['#7c3aed','#db2777','#d97706','#0369a1','#059669','#dc2626'];
var SENDER_CLR={},sci=0;
function convClr(id,cat){return CAT_CLR[cat]||ID_CLR[id%ID_CLR.length];}
function senderClr(n){if(!SENDER_CLR[n])SENDER_CLR[n]=SC_CLR[sci++%SC_CLR.length];return SENDER_CLR[n];}
function catLabel(c){return{team:'Team Chat',resident:'Resident Care',alerts:'System Alerts'}[c]||'Chat';}
async function loadConvs(){
  try{var r=await fetch(API_BASE+'/messages/conversations',{headers:authH()});if(!r.ok)throw new Error();var d=await r.json();
    if(d.length){allConvs=d.map(function(c){return{id:c.id,name:c.name,category:c.category,last_message:c.last_message||'',last_message_at:c.last_message_at||'',unread_count:c.unread_count||0,sub:catLabel(c.category),color:convClr(c.id,c.category),online:false};});demo=false;}
    else throw new Error();
  }catch(e){allConvs=DEMO_CONVS.map(function(c){return Object.assign({},c);});demo=true;}
  updateLabel();filterConvs();
}
function updateLabel(){var t=allConvs.reduce(function(s,c){return s+(c.unread_count||0);},0);document.getElementById('unread-label').textContent=t?t+' unread message'+(t!==1?'s':''):'All caught up';}
function setCat(cat,btn){currentCat=cat;document.querySelectorAll('.cat-tab').forEach(function(b){b.classList.remove('active');});btn.classList.add('active');filterConvs();}
function filterConvs(){var q=document.getElementById('conv-search').value.toLowerCase();filteredConvs=allConvs.filter(function(c){if(currentCat&&c.category!==currentCat)return false;if(q&&!c.name.toLowerCase().includes(q)&&!(c.last_message||'').toLowerCase().includes(q))return false;return true;});renderConvList();}
function renderConvList(){var el=document.getElementById('conv-list');if(!filteredConvs.length){el.innerHTML='<div style="text-align:center;padding:40px 20px;color:var(--text3);font-size:13px;">No conversations found</div>';return;}el.innerHTML=filteredConvs.map(function(c){var isAlert=c.category==='alerts';var badge=c.unread_count>0?'<div class="unread-badge">'+c.unread_count+'</div>':'';var dot=c.online?'<div class="online-dot"></div>':'';return'<div class="conv-item'+(c.id===currentId?' active':'')+'" onclick="openConv('+c.id+')">'+'<div class="conv-av'+(isAlert?' alert-av':'')+'" style="background:'+(isAlert?'':c.color)+'">'+ini(c.name)+dot+'</div>'+'<div class="conv-body">'+'<div class="conv-name-row"><div class="conv-name'+(c.unread_count>0?' unread':'')+'">'+esc(c.name)+'</div><div class="conv-time">'+(c.last_message_at||'')+'</div></div>'+'<div class="conv-preview-row"><div class="conv-preview">'+esc(c.last_message||'')+'</div>'+badge+'</div>'+'</div></div>';}).join('');}
async function openConv(id){currentId=id;var conv=allConvs.find(function(c){return c.id===id;});if(!conv)return;conv.unread_count=0;updateLabel();renderConvList();try{if(!demo)await fetch(API_BASE+'/messages/conversations/'+id+'/read',{method:'PATCH',headers:authH()});}catch(e){}document.getElementById('chat-empty').style.display='none';var cv=document.getElementById('chat-view');cv.style.display='flex';document.getElementById('ch-av').textContent=ini(conv.name);document.getElementById('ch-av').style.background=conv.color;document.getElementById('ch-name').textContent=conv.name;document.getElementById('ch-sub').textContent=conv.sub||catLabel(conv.category);await loadMsgs(id);document.getElementById('msg-input').focus();}
async function loadMsgs(id){if(localMsgs[id]){renderMsgs(localMsgs[id]);return;}try{if(demo)throw new Error();var r=await fetch(API_BASE+'/messages/conversations/'+id+'/messages',{headers:authH()});if(!r.ok)throw new Error();localMsgs[id]=await r.json();}catch(e){localMsgs[id]=(DEMO_MSGS[id]||[]).map(function(m){return Object.assign({},m);});}renderMsgs(localMsgs[id]);}
function fmtTime(t){if(typeof t==='string')return t;try{return new Date(t).toLocaleTimeString('en-AU',{hour:'2-digit',minute:'2-digit'});}catch(e){return '';}}
function makeFileBubble(fname,furl){var fullUrl=furl.startsWith('http')?furl:API_BASE+furl;var ext=fname.split('.').pop().toLowerCase();var isImg=['jpg','jpeg','png','gif','webp','bmp','svg'].includes(ext);var isVid=['mp4','mov','avi','webm','mpeg'].includes(ext);if(isImg)return'<img class="img-bubble" src="'+fullUrl+'" alt="'+esc(fname)+'" onclick="window.open(\''+fullUrl+'\')"/>';if(isVid)return'<video class="vid-bubble" src="'+fullUrl+'" controls></video>';return'<a class="file-bubble" href="'+fullUrl+'" download="'+esc(fname)+'" target="_blank"><div class="file-bubble-icon"><svg viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg></div><div><div class="file-bubble-name">'+esc(fname)+'</div><div class="file-bubble-size">Tap to download</div></div></a>';}
function localFileBubble(f){if(f.type==='image')return'<img class="img-bubble" src="'+f.objectUrl+'" alt="'+esc(f.file.name)+'" onclick="window.open(\''+f.objectUrl+'\')"/>';if(f.type==='video')return'<video class="vid-bubble" src="'+f.objectUrl+'" controls></video>';return'<a class="file-bubble" href="'+f.objectUrl+'" download="'+esc(f.file.name)+'" target="_blank"><div class="file-bubble-icon"><svg viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg></div><div><div class="file-bubble-name">'+esc(f.file.name)+'</div><div class="file-bubble-size">'+fmtSize(f.file.size)+'</div></div></a>';}
function renderMsgs(msgs,hl){var el=document.getElementById('chat-messages');if(!msgs.length){el.innerHTML='<div style="text-align:center;padding:40px;color:var(--text3);font-size:13px;">No messages yet. Say hello!</div>';return;}var html='<div class="date-div">Today</div>';msgs.forEach(function(m,i){var isSelf=m.is_self==='true'||m.is_self===true;var clr=isSelf?'#2ec4b6':senderClr(m.sender_name);var t=fmtTime(m.created_at);var showName=!isSelf&&(i===0||msgs[i-1].sender_name!==m.sender_name||msgs[i-1].is_self==='true');var tick=isSelf?'<span class="tick"><svg viewBox="0 0 24 24"><polyline points="20 6 9 17 4 12"/></svg></span>':'';var bubbleHtml;if(m.fileHtml){bubbleHtml=m.fileHtml;}else if(m.content&&m.content.startsWith('[file] ')){var parts=m.content.slice(7).split(' | ');bubbleHtml=makeFileBubble(parts[0]||'file',parts[1]||'');}else{var txt=esc(m.content||'');if(hl)txt=txt.replace(new RegExp(esc(hl).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'gi'),function(s){return'<mark style="background:#fef08a;border-radius:3px;">'+s+'</mark>';});bubbleHtml=isSelf?'<div class="bubble self">'+txt+'</div>':'<div class="bubble other">'+txt+'</div>';}if(isSelf){html+='<div class="msg-row self"><div class="msg-col">'+bubbleHtml+'<div class="msg-meta" style="justify-content:flex-end"><div class="msg-time">'+t+'</div>'+tick+'</div></div></div>';}else{html+='<div class="msg-row"><div class="msg-av" style="background:'+clr+'">'+ini(m.sender_name)+'</div><div class="msg-col">'+(showName?'<div class="msg-sender">'+esc(m.sender_name)+' - '+esc(m.sender_role||'')+'</div>':'')+bubbleHtml+'<div class="msg-meta"><div class="msg-time">'+t+'</div></div></div></div>';}});el.innerHTML=html;scrollBottom();}
function handleFiles(files){if(!currentId){alert('Please select a conversation first.');return;}Array.from(files).forEach(function(file){var type=file.type.startsWith('image/')?'image':file.type.startsWith('video/')?'video':'doc';pendingFiles.push({file:file,objectUrl:URL.createObjectURL(file),type:type});});document.getElementById('file-input').value='';renderFilePreview();}
function renderFilePreview(){var strip=document.getElementById('file-preview-strip');if(!pendingFiles.length){strip.style.display='none';return;}strip.style.display='flex';strip.innerHTML=pendingFiles.map(function(f,i){var inner;if(f.type==='image')inner='<img src="'+f.objectUrl+'" alt="'+esc(f.file.name)+'"/>';else if(f.type==='video')inner='<video src="'+f.objectUrl+'" muted></video>';else inner='<div class="fp-doc"><svg viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg><div class="fp-doc-name">'+esc(f.file.name)+'</div></div>';return'<div class="fp-item">'+inner+'<button class="fp-remove" onclick="removePending('+i+')">x</button></div>';}).join('');}
function removePending(i){URL.revokeObjectURL(pendingFiles[i].objectUrl);pendingFiles.splice(i,1);renderFilePreview();}
function handleKey(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage();}}
async function sendMessage(){var input=document.getElementById('msg-input');var content=input.value.trim();if(!content&&!pendingFiles.length)return;if(!currentId)return;input.value='';autoResize(input);var now=new Date().toLocaleTimeString('en-AU',{hour:'2-digit',minute:'2-digit'});if(!localMsgs[currentId])localMsgs[currentId]=[];var filesToSend=pendingFiles.slice();pendingFiles=[];renderFilePreview();
  for(var i=0;i<filesToSend.length;i++){var f=filesToSend[i];var tempMsg={id:Date.now()+Math.random(),conversation_id:currentId,sender_name:ME.name,sender_role:ME.role,content:'',is_self:'true',created_at:now,fileHtml:localFileBubble(f)};localMsgs[currentId].push(tempMsg);
    try{if(!demo){var form=new FormData();form.append('file',f.file);var res=await fetch(API_BASE+'/messages/upload',{method:'POST',headers:authHF(),body:form});if(res.ok){var info=await res.json();tempMsg.fileHtml=makeFileBubble(info.filename,info.url);var mc='[file] '+info.filename+' | '+info.url;await fetch(API_BASE+'/messages/conversations/'+currentId+'/messages',{method:'POST',headers:authH(),body:JSON.stringify({conversation_id:currentId,sender_name:ME.name,sender_role:ME.role,content:mc,is_self:'true'})});}}}catch(e){}}
  if(filesToSend.length&&!content){var conv0=allConvs.find(function(c){return c.id===currentId;});if(conv0){conv0.last_message='[File] '+filesToSend[0].file.name;conv0.last_message_at=now;}}
  if(content){var msg={id:Date.now(),conversation_id:currentId,sender_name:ME.name,sender_role:ME.role,content:content,is_self:'true',created_at:now};localMsgs[currentId].push(msg);var conv1=allConvs.find(function(c){return c.id===currentId;});if(conv1){conv1.last_message=content;conv1.last_message_at=now;}try{if(!demo)await fetch(API_BASE+'/messages/conversations/'+currentId+'/messages',{method:'POST',headers:authH(),body:JSON.stringify({conversation_id:currentId,sender_name:ME.name,sender_role:ME.role,content:content,is_self:'true'})});}catch(e){}}
  renderMsgs(localMsgs[currentId]);renderConvList();}
function autoResize(el){el.style.height='auto';el.style.height=Math.min(el.scrollHeight,120)+'px';}
function markCurrentUnread(){if(!currentId)return;var c=allConvs.find(function(x){return x.id===currentId;});if(!c)return;c.unread_count=(c.unread_count||0)+1;updateLabel();renderConvList();}
function markCurrentRead(){if(!currentId)return;var c=allConvs.find(function(x){return x.id===currentId;});if(!c)return;c.unread_count=0;updateLabel();renderConvList();try{if(!demo)fetch(API_BASE+'/messages/conversations/'+currentId+'/read',{method:'PATCH',headers:authH()});}catch(e){}}
function toggleMsgSearch(){var bar=document.getElementById('msg-search-bar');var open=bar.style.display==='none'||bar.style.display==='';bar.style.display=open?'block':'none';if(open)document.getElementById('msg-search-input').focus();else{document.getElementById('msg-search-input').value='';renderMsgs(localMsgs[currentId]||[]);}}
function searchInChat(){var q=document.getElementById('msg-search-input').value.trim();renderMsgs(localMsgs[currentId]||[],q);}
function showCtx(e){e.stopPropagation();var m=document.getElementById('ctx');m.style.top=e.clientY+'px';m.style.left=Math.max(0,e.clientX-180)+'px';m.classList.add('show');}
function hideCtx(){document.getElementById('ctx').classList.remove('show');}
document.addEventListener('click',hideCtx);
async function deleteConv(){if(!currentId)return;if(!confirm('Delete this conversation?'))return;try{if(!demo)await fetch(API_BASE+'/messages/conversations/'+currentId,{method:'DELETE',headers:authH()});}catch(e){}allConvs=allConvs.filter(function(c){return c.id!==currentId;});delete localMsgs[currentId];currentId=null;document.getElementById('chat-view').style.display='none';document.getElementById('chat-empty').style.display='flex';updateLabel();filterConvs();}
function openNewModal(){document.getElementById('new-name').value='';document.getElementById('modal-new').classList.add('open');setTimeout(function(){document.getElementById('new-name').focus();},80);}
function closeModal(id){document.getElementById(id).classList.remove('open');}
async function createConv(){var name=document.getElementById('new-name').value.trim();var cat=document.getElementById('new-cat').value;if(!name){document.getElementById('new-name').focus();return;}var newId=Date.now();try{if(!demo){var r=await fetch(API_BASE+'/messages/conversations',{method:'POST',headers:authH(),body:JSON.stringify({name:name,category:cat})});if(r.ok){var d=await r.json();newId=d.id;}}}catch(e){}var c={id:newId,name:name,category:cat,last_message:'',last_message_at:'Just now',unread_count:0,sub:catLabel(cat),color:convClr(newId,cat),online:false};allConvs.unshift(c);localMsgs[newId]=[];filterConvs();closeModal('modal-new');openConv(newId);}
document.addEventListener('DOMContentLoaded',function(){var area=document.getElementById('chat-messages');if(!area)return;area.addEventListener('dragover',function(e){e.preventDefault();area.classList.add('drag-over');});area.addEventListener('dragleave',function(){area.classList.remove('drag-over');});area.addEventListener('drop',function(e){e.preventDefault();area.classList.remove('drag-over');if(e.dataTransfer.files.length)handleFiles(e.dataTransfer.files);});});
loadConvs();
