/**
 * CallSummaryModal.tsx
 *
 * Post-call AI summary modal.
 * The real AI summary is generated by the backend and sent to chat there.
 * The mobile app only displays the patient-safe summary and never calls LLM APIs.
 */

import { useCallback, useEffect, useRef, useState } from "react";
import {
  View,
  Text,
  StyleSheet,
  Pressable,
  ScrollView,
  ActivityIndicator,
  Share,
} from "react-native";
import { Feather, MaterialIcons } from "@expo/vector-icons";
import { colors } from "../../theme/colors";
import { callService } from "../../services/callService";
import { wsClient } from "../../services/wsClient";
import type { TranscriptItem, CallContact, CallSession } from "../../types/call";

// ─── Types ────────────────────────────────────────────────────────────────────

type CallSummaryModalProps = {
  visible: boolean;
  onClose: () => void;
  session: CallSession | null;
  contact: CallContact | null;
  transcriptItems: TranscriptItem[];
  formattedDuration: string;
};

type SummaryState =
  | { status: "idle" }
  | { status: "generating" }
  | { status: "done"; text: string }
  | { status: "error"; message: string };

type ChatSendState = "idle" | "waiting" | "sent" | "error";

// ─── Helpers ──────────────────────────────────────────────────────────────────

function formatTranscriptLine(item: TranscriptItem): string {
  const tag = item.source === "asl" || item.content.startsWith("[ASL]") ? "ASL" : "Speech";
  return `${item.speaker} (${tag}): ${item.content}`;
}

function buildLocalFallbackSummary(
  transcriptItems: TranscriptItem[],
  session: CallSession | null,
  contact: CallContact | null,
  duration: string
): string {
  const callType = session?.mode === "video" ? "Video" : "Audio";
  const providerName = contact?.name ?? session?.doctor?.name ?? "Provider";
  const patientName = session?.patient?.name ?? "Patient";
  const cleanItems = transcriptItems
    .filter((item) => item.content?.trim())
    .filter((item) => item.isFinal !== false);
  const keyLines = cleanItems.slice(-6).map(formatTranscriptLine);

  return [
    `${callType} call summary is still being generated by the backend.`,
    `Duration: ${duration}. Provider: ${providerName}. Patient: ${patientName}.`,
    "",
    "Recent transcript lines",
    ...(keyLines.length > 0
      ? keyLines.map((line) => `• ${line}`)
      : ["• No transcript was captured on this screen yet."]),
    "",
    "The official AI summary will be sent to the conversation by the backend once it is ready.",
  ].join("\n");
}

function extractSummaryText(source: any): string | null {
  if (!source) return null;

  const direct = source.patient_summary ?? source.patientSummary ?? source.ai_summary;
  if (typeof direct === "string" && direct.trim()) {
    const trimmed = direct.trim();
    try {
      const parsed = JSON.parse(trimmed);
      const fromJson = parsed.patient_summary ?? parsed.patientSummary ?? parsed.ai_summary ?? parsed.summary;
      if (typeof fromJson === "string" && fromJson.trim()) return fromJson.trim();
    } catch {}
    return trimmed;
  }

  if (typeof source.ai_summary === "object") {
    const nested = source.ai_summary.patient_summary ?? source.ai_summary.patientSummary ?? source.ai_summary.summary;
    if (typeof nested === "string" && nested.trim()) return nested.trim();
  }

  return null;
}

function getPayloadCallId(payload: any): number | null {
  const value = Number(payload?.call_id ?? payload?.callId);
  return Number.isFinite(value) ? value : null;
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function CallSummaryModal({
  visible,
  onClose,
  session,
  contact,
  transcriptItems,
  formattedDuration,
}: CallSummaryModalProps) {
  const [summary, setSummary] = useState<SummaryState>({ status: "idle" });
  const [sentToChat, setSentToChat] = useState<ChatSendState>("idle");
  const hasStarted = useRef(false);
  const pollTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const clearPollTimer = useCallback(() => {
    if (!pollTimer.current) return;
    clearTimeout(pollTimer.current);
    pollTimer.current = null;
  }, []);

  const applyBackendSummary = useCallback((payload: any) => {
    const text = extractSummaryText(payload);
    if (!text) return false;

    setSummary({ status: "done", text });
    setSentToChat(payload?.message_id || payload?.message_conversation_id || payload?.ai_summary ? "sent" : "waiting");
    return true;
  }, []);

  const pollBackendSummary = useCallback((attempt = 0) => {
    if (!session?.callId) return;

    callService
      .getCall(session.callId)
      .then((data) => {
        const ok = applyBackendSummary(data);
        if (ok) return;

        if (attempt >= 10) {
          setSummary({
            status: "done",
            text: buildLocalFallbackSummary(transcriptItems, session, contact, formattedDuration),
          });
          setSentToChat("waiting");
          return;
        }

        pollTimer.current = setTimeout(() => pollBackendSummary(attempt + 1), 1800);
      })
      .catch(() => {
        if (attempt >= 5) {
          setSummary({
            status: "error",
            message: "Unable to load the backend AI summary. Please check the chat later.",
          });
          setSentToChat("error");
          return;
        }
        pollTimer.current = setTimeout(() => pollBackendSummary(attempt + 1), 2000);
      });
  }, [applyBackendSummary, contact, formattedDuration, session, transcriptItems]);

  const generateSummary = useCallback(() => {
    if (!session?.callId) {
      setSummary({
        status: "done",
        text: buildLocalFallbackSummary(transcriptItems, session, contact, formattedDuration),
      });
      setSentToChat("idle");
      return;
    }

    clearPollTimer();
    setSummary({ status: "generating" });
    setSentToChat("waiting");
    pollBackendSummary(0);
  }, [clearPollTimer, contact, formattedDuration, pollBackendSummary, session, transcriptItems]);

  useEffect(() => {
    if (!visible) {
      hasStarted.current = false;
      clearPollTimer();
      return;
    }

    if (!hasStarted.current) {
      hasStarted.current = true;
      generateSummary();
    }

    const unsubscribe = wsClient.subscribe("call.summary_ready", (payload) => {
      if (!session?.callId) return;
      if (getPayloadCallId(payload) !== session.callId) return;
      clearPollTimer();
      applyBackendSummary(payload);
    });

    wsClient.connect().catch(() => undefined);

    return () => {
      unsubscribe();
      clearPollTimer();
    };
  }, [applyBackendSummary, clearPollTimer, generateSummary, session?.callId, visible]);

  // ── Share ───────────────────────────────────────────────────────────────────

  const handleShare = useCallback(async () => {
    if (summary.status !== "done") return;

    const doctorName = contact?.name ?? session?.doctor?.name ?? "Provider";
    const patientName = session?.patient?.name ?? "Patient";
    const date = new Date().toLocaleDateString("en-AU");

    const shareText = [
      "Telehealth Consultation Summary",
      `Date: ${date} · Duration: ${formattedDuration}`,
      `Provider: ${doctorName} · Patient: ${patientName}`,
      "",
      summary.text,
    ].join("\n");

    try {
      await Share.share({
        title: `Consultation Summary – ${date}`,
        message: shareText,
      });
    } catch {
      // dismissed
    }
  }, [summary, contact, session, formattedDuration]);

  // ── Render ──────────────────────────────────────────────────────────────────

  if (!visible) return null;

  const callType = session?.mode === "video" ? "Video" : "Audio";
  const doctorName = contact?.name ?? session?.doctor?.name ?? "Provider";
  const date = new Date().toLocaleDateString("en-AU", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
  const isDone = summary.status === "done";

  return (
    <View style={styles.overlay}>
      <View style={styles.container}>
        {/* Header */}
        <View style={styles.header}>
          <View style={styles.headerLeft}>
            <View style={styles.headerIconWrap}>
              <MaterialIcons name="summarize" size={20} color={colors.primary} />
            </View>
            <View>
              <Text style={styles.headerTitle}>Call Summary</Text>
              <Text style={styles.headerSubtitle}>
                {callType} · {date} · {formattedDuration}
              </Text>
            </View>
          </View>
          <Pressable style={styles.closeBtn} onPress={onClose}>
            <Feather name="x" size={20} color={colors.textMuted} />
          </Pressable>
        </View>

        {/* Provider pill */}
        <View style={styles.metaRow}>
          <View style={styles.metaPill}>
            <View
              style={[
                styles.avatar,
                { backgroundColor: contact?.avatarColor ?? colors.primary },
              ]}
            >
              <Text style={styles.avatarText}>{contact?.initials ?? "DR"}</Text>
            </View>
            <Text style={styles.metaPillText}>{doctorName}</Text>
          </View>
          <View style={styles.transcriptCount}>
            <Feather name="message-square" size={13} color={colors.textMuted} />
            <Text style={styles.transcriptCountText}>
              {transcriptItems.length} entries
            </Text>
          </View>
        </View>

        {/* Body */}
        <ScrollView
          style={styles.body}
          contentContainerStyle={styles.bodyContent}
          showsVerticalScrollIndicator={false}
        >
          {/* AI Summary section */}
          <View style={styles.section}>
            <View style={styles.sectionHeader}>
              <MaterialIcons name="smart-toy" size={16} color={colors.primary} />
              <Text style={styles.sectionTitle}>Backend AI Summary</Text>
            </View>

            {summary.status === "generating" && (
              <View style={styles.loadingWrap}>
                <ActivityIndicator size="small" color={colors.primary} />
                <Text style={styles.loadingText}>Waiting for backend summary…</Text>
              </View>
            )}

            {summary.status === "done" && (
              <View style={styles.summaryCard}>
                <Text style={styles.summaryText}>{summary.text}</Text>
              </View>
            )}

            {summary.status === "error" && (
              <View style={styles.errorCard}>
                <Feather name="alert-circle" size={16} color={colors.danger} />
                <Text style={styles.errorText}>{summary.message}</Text>
                <Pressable style={styles.retryBtn} onPress={generateSummary}>
                  <Text style={styles.retryBtnText}>Retry</Text>
                </Pressable>
              </View>
            )}

            {summary.status === "idle" && (
              <Pressable style={styles.generateBtn} onPress={generateSummary}>
                <MaterialIcons name="smart-toy" size={16} color={colors.surface} />
                <Text style={styles.generateBtnText}>Load Summary</Text>
              </Pressable>
            )}
          </View>

          {/* Transcript section */}
          {transcriptItems.length > 0 && (
            <View style={styles.section}>
              <View style={styles.sectionHeader}>
                <Feather name="file-text" size={16} color={colors.primary} />
                <Text style={styles.sectionTitle}>Full Transcript</Text>
              </View>
              {transcriptItems
                .filter((i) => i.content?.trim())
                .map((item) => {
                  const isLocal = item.role === "patient";
                  return (
                    <View
                      key={`${item.id}-${item.segmentId ?? ""}`}
                      style={[
                        styles.transcriptBubble,
                        isLocal && styles.transcriptBubbleLocal,
                      ]}
                    >
                      <View style={styles.transcriptBubbleHeader}>
                        <Text
                          style={[
                            styles.transcriptSpeaker,
                            isLocal && styles.transcriptSpeakerLocal,
                          ]}
                        >
                          {item.speaker}
                        </Text>
                        {item.source === "asl" && (
                          <View style={styles.aslTag}>
                            <Text style={styles.aslTagText}>ASL</Text>
                          </View>
                        )}
                        <Text style={styles.transcriptTime}>
                          {new Date(item.created_at).toLocaleTimeString("en-AU", {
                            hour: "2-digit",
                            minute: "2-digit",
                          })}
                        </Text>
                      </View>
                      <Text style={styles.transcriptContent}>{item.content}</Text>
                    </View>
                  );
                })}
            </View>
          )}

          <View style={{ height: 20 }} />
        </ScrollView>

        {/* Footer */}
        <View style={styles.footer}>
          {/* Chat send status indicator */}
          <View style={styles.chatStatusRow}>
            {sentToChat === "waiting" && (
              <>
                <ActivityIndicator size="small" color={colors.primary} />
                <Text style={styles.chatStatusText}>Backend will send this to chat…</Text>
              </>
            )}
            {sentToChat === "sent" && (
              <>
                <Feather name="check-circle" size={15} color={colors.success} />
                <Text style={[styles.chatStatusText, styles.chatStatusSent]}>
                  Sent to chat by backend
                </Text>
              </>
            )}
            {sentToChat === "error" && (
              <>
                <Feather name="alert-circle" size={15} color={colors.danger} />
                <Text style={[styles.chatStatusText, styles.chatStatusError]}>
                  Chat delivery not confirmed
                </Text>
              </>
            )}
          </View>

          {/* Action buttons */}
          <View style={styles.footerBtns}>
            <Pressable
              style={[styles.actionBtn, !isDone && styles.actionBtnDisabled]}
              onPress={handleShare}
              disabled={!isDone}
            >
              <Feather
                name="share-2"
                size={18}
                color={isDone ? colors.surface : colors.textMuted}
              />
              <Text
                style={[styles.actionBtnText, !isDone && styles.actionBtnTextDisabled]}
              >
                Share
              </Text>
            </Pressable>

            <Pressable style={styles.closeFooterBtn} onPress={onClose}>
              <Text style={styles.closeFooterBtnText}>Done</Text>
            </Pressable>
          </View>
        </View>
      </View>
    </View>
  );
}

// ─── Styles ───────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 999,
    elevation: 20,
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 14,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  headerIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#EEF2FF",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: colors.textSecondary,
  },
  headerSubtitle: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 1,
  },
  closeBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.backgroundAlt,
    alignItems: "center",
    justifyContent: "center",
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  metaPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  avatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.surface,
  },
  metaPillText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  transcriptCount: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  transcriptCountText: {
    fontSize: 13,
    color: colors.textMuted,
  },
  body: {
    flex: 1,
  },
  bodyContent: {
    padding: 20,
    gap: 20,
  },
  section: {
    gap: 10,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.textSecondary,
  },
  loadingWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 16,
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  loadingText: {
    fontSize: 14,
    color: colors.textMuted,
  },
  summaryCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  summaryText: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 22,
  },
  errorCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: "#FFF5F5",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "#FCA5A5",
    flexWrap: "wrap",
  },
  errorText: {
    fontSize: 13,
    color: colors.danger,
    flex: 1,
  },
  retryBtn: {
    marginTop: 8,
    backgroundColor: colors.danger,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  retryBtnText: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.surface,
  },
  generateBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 14,
  },
  generateBtnText: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.surface,
  },
  transcriptBubble: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  transcriptBubbleLocal: {
    backgroundColor: "#EEF2FF",
    borderColor: "#D6DEFF",
  },
  transcriptBubbleHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  transcriptSpeaker: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  transcriptSpeakerLocal: {
    color: colors.primary,
  },
  aslTag: {
    backgroundColor: "#E0EAFF",
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 1,
  },
  aslTagText: {
    fontSize: 9,
    fontWeight: "800",
    color: colors.primary,
    letterSpacing: 0.4,
  },
  transcriptTime: {
    fontSize: 11,
    color: colors.textMuted,
    flex: 1,
    textAlign: "right",
  },
  transcriptContent: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
  },
  footer: {
    paddingHorizontal: 20,
    paddingVertical: 14,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    gap: 10,
  },
  chatStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minHeight: 20,
  },
  chatStatusText: {
    fontSize: 13,
    color: colors.textMuted,
  },
  chatStatusSent: {
    color: colors.success,
    fontWeight: "600",
  },
  chatStatusError: {
    color: colors.danger,
  },
  chatStatusRetry: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.primary,
    marginLeft: 4,
  },
  footerBtns: {
    flexDirection: "row",
    gap: 8,
  },
  actionBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 11,
    paddingHorizontal: 16,
  },
  actionBtnSecondary: {
    backgroundColor: "#EEF2FF",
    borderWidth: 1,
    borderColor: "#D6DEFF",
  },
  actionBtnDisabled: {
    backgroundColor: colors.backgroundAlt,
  },
  actionBtnText: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.surface,
  },
  actionBtnTextSecondary: {
    color: colors.primary,
  },
  actionBtnTextDisabled: {
    color: colors.textMuted,
  },
  closeFooterBtn: {
    paddingHorizontal: 16,
    paddingVertical: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.backgroundAlt,
    borderRadius: 14,
  },
  closeFooterBtnText: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.textSecondary,
  },
});