import {
  acceptCall,
  applyRealtimeCallState,
  cancelCall,
  declineCall,
  endCall,
  fetchCall,
  fetchCallContactById,
  fetchCallContacts,
  fetchCallSummary,
  fetchTranscript,
  getCallStatusLabel,
  muteCall,
  parseIncomingInvite,
  resolveIncomingCallContact,
  startCall,
  stopCall,
  updateCallMode,
} from "../api/call";

export const callService = {
  getSummary: fetchCallSummary,
  getContacts: fetchCallContacts,
  getContactById: fetchCallContactById,
  resolveIncomingContact: resolveIncomingCallContact,
  startCall,
  acceptCall,
  getCall: fetchCall,
  getTranscript: fetchTranscript,
  muteCall,
  endCall,
  stopCall,
  updateMode: updateCallMode,
  cancelCall,
  declineCall,
  applyRealtimeCallState,
  parseIncomingInvite,
  getCallStatusLabel,
};